services:
  client:
    container_name: react-client
    build:
      context: ./client
    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    networks:
      - postgres-network

  express:
    container_name: express-server
    build:
      context: ./server
    ports:
      - "8080:8080"

    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: mydb
      REDIS_SERVER_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - postgres-network

  postgres:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  pgdata:
